### PR TITLE
[BBC-11002] (chore): fix build warnings

### PR DESCRIPTION
**Pull request by gabrielagabriel**
## Description

All components have had missing properties on building

## What has been done

- Export type from index

// Before
`export { ActionNames, ActionTypes } from "./ActionTypes";`

// Above line resulted in warning
`// > "export 'ActionPayload' was not found in './ActionTypes'`

// Changed the code to the following for the warning to disappear
```
export { ActionNames } from "./ActionTypes";
export type ActionPayload = ActionPayload;
```

## Things to consider

- Now we have a lint issue on circularly references

```
src/topBar/index.tsx:2:13 - error TS2456: Type alias 'TopBarProps' circularly references itself.

2 export type TopBarProps = TopBarProps
```

Need help from ts experts @simonrelet @mcellier 

## How it was tested

- Storybook compiling (npm start)

### CODE REVIEW

**Comment by simonrelet** [comment]
I'm not sure to understand the issue.
Is it in the build of the library or in the build of an application using the library?

In the example of the description:

```ts
export { ActionNames } from "./ActionTypes";
export type ActionPayload = ActionPayload;
//                          ^  Doesn't exist, I'm not sure how it this should work
```

**Comment by gabrielagabriel** [comment]
> I'm not sure to understand the issue.
> Is it in the build of the library or in the build of an application using the library?
> 
> In the example of the description:
> 
> ```ts
> export { ActionNames } from "./ActionTypes";
> export type ActionPayload = ActionPayload;
> //                          ^  Doesn't exist, I'm not sure how it this should work
> ```

The issue is the warnings on building this application (ui-library) I'm updating description with the screenshots of the issue to better understanding

**Comment by Tip-Sy** [comment]
Question: is there a way to automate/control that with an eslint rule to avoid regressions later on?

**Comment by gabrielagabriel** [comment]
This solution has been rejected

**Pull request closed without merging**
