### PR TITLE
ran npm audit fix for new prototype pollution vulnerability

### PR DESCRIPTION
**Pull request by Tuxosaurus**
Mostly because of https://snyk.io/vuln/SNYK-JS-MIXINDEEP-450212

### CODE REVIEW

**Comment by pith** [comment]
There is no update on the `package.json`

**Comment by Tuxosaurus** [comment]
> There is no update on the `package.json`

`npm audit fix` didn't make any change to `package.json`
It seems the faulty packages were found in jest so I'm still gonna bump everything related to jest (from 24.5.0 to 24.8.0) just in case

**Comment by PerrineBoissieres** [comment]
> > There is no update on the `package.json`
> 
> `npm audit fix` didn't make any change to `package.json`
> It seems the faulty packages were found in jest so I'm still gonna bump everything related to jest (from 24.5.0 to 24.8.0) just in case (but just updating Jest doesn't fix the issue)

Seems good to me, then :)

**Comment by Tuxosaurus** [comment]
I added a new line in the Changelog

**Pull request merged**
